### ISSUE TITLE
Why is a thank you page required? How can we show the thank you message inside the comeet iframe instead?

### ISSUE THREAD

**Issue by atera-web** [ComeetCo/comeet-wp-plugin#10]

**Comment by YonatanRan** [comment]
The thank you page ins't required. If a thank you page isn't supplied, the iFrame will display a thank you message.
The thank you page option exists so that the user can be redirected to a specified page (The thank you page) where you can have different tracking codes, pixels and special messages that you might want to display to the user.

If you want a thank you message in the same page - do not set the hank you page option.

**Comment by atera-web** [comment]
Hi, this doesn't seem to be correct. 
If you look at the relevant function in comeet.php you'll see some url is generated in case the field isn't set:
https://github.com/ComeetCo/comeet-wp-plugin/blob/24ca010ebd7619a05c9de6a78dcb30993aa6e6e9/comeet.php#L1199

If I remove the thankyou-url param manually from the iframe then it does work in the way you described.

**Comment by YonatanRan** [comment]
Hi @atera-web You seem to be correct. 

This will be fixed very soon in a plugin update.

Thanks for letting me know.

**Comment by YonatanRan** [comment]
Hi @atera-web,

The plugin has been updated. The latest version (2.3.6) now works as expected.
If you do not specify a thank you page, the user will remain on the same page and a thank you message will replace the application form.
